### ISSUE TITLE
Nest 8 + redis bug

### ISSUE THREAD

**Issue by herenickname** [skunight/nestjs-redis#82] opened 2021-07-09 00:46 UTC
[Nest] 2697522  - 07/09/2021, 12:43:37 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the RedisCoreModule (Symbol(REDIS_MODULE_OPTIONS), ?). Please make sure that the argument ModuleRef at index [1] is available in the RedisCoreModule context.

Potential solutions:
- If ModuleRef is a provider, is it part of the current RedisCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within RedisCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })

**Comment by aoxiang78** [comment] 2021-07-09 06:29
Stopped here, there is no way to continue, do you have a temporary solution?

**Comment by rares-lupascu** [comment] 2021-07-09 08:31
i personally duplicated this module into my local nestjs project

**Comment by aoxiang78** [comment] 2021-07-10 00:14
@rares-lupascu Which files have you updated? Can you share it? I haven't solved this problem

**Comment by rares-lupascu** [comment] 2021-07-10 17:58
@aoxiang78  ok might sound weird but just add this to `redis-core.module.ts`:
1) `import { ConfigModule } from '@nestjs/config';`
2) in the module definition .... change this
```
@Module({
  providers: [RedisService],
  exports: [RedisService],
})
```
to this (line 20):
```
@Module({
    providers: [RedisService],
    exports: [RedisService],
    imports: [ConfigModule],
})
```

**Comment by aoxiang78** [comment] 2021-07-12 02:47
Solved it your way, thank you for your help @rares-lupascu

**Comment by brandongit2** [comment] 2021-07-12 05:01
@rares-lupascu That doesn't seem to be working for me. Could you explain how adding `ConfigModule` to the imports solves NestJS looking for `ModuleRef`? That part confuses me.

**Comment by rares-lupascu** [comment] 2021-07-12 06:48
@brandongit2 what I did was to create a local Redis module copying the contents of this repo into it (the lib folder) and applying the change I did at the top ... hope this helps

**Comment by alikil** [comment] 2021-07-13 00:46
I cannot use this solution at production build.
Still waiting for this library fix.

**Comment by liaoliaots** [comment] 2021-07-13 08:35
[@liaoliaots/nestjs-redis v3.0.0-next.2 has been released.](https://www.npmjs.com/package/@liaoliaots/nestjs-redis/v/3.0.0-next.2)

**Comment by PraveenKumarPalai** [comment] 2021-07-16 13:01
@rares-lupascu Nice workaround for local 😎 !!

But for production, when can we expect a fix on this?

**Comment by bangbang93** [comment] 2021-07-19 02:12
Keep watching. We are migrating to nestjs 8 and stuck on this.

**Comment by GyanendroKh** [comment] 2021-07-25 05:05
Instead of using `ModuleRef` to get the `RedisClient`, the `RedisClient` could be directly injected using `@Inject(REDIS_CLIENT)`. And this solves the problem. I opened a pull request #85. 

For now I'm using the library by directly downloading it from my Github [Repo](https://github.com/GyanendroKh/nestjs-redis.git). Hope it will be released soon.
```json
{
  "dependencies": {
    "nestjs-redis": "git+https://github.com/GyanendroKh/nestjs-redis.git#nest8-fix",
  }
}
```

**Comment by cdlaiqi** [comment] 2021-07-30 17:51
@rares-lupascu solved the problem, thank you

**Comment by nolawnchairs** [comment] 2021-07-31 16:16
It's been over two years since the last release was published, so I personally consider this project abandoned.

**Comment by SampaioLeal** [comment] 2021-08-03 21:11
> It's been over two years since the last release was published, so I personally consider this project abandoned.

you mean the 1.3.3 4 months ago?

**Comment by Yurko-Fedoriv** [comment] 2021-09-07 06:53
Adding here: actually, no code change is required, and lib just needs to be recompiled with updated dependencies.
If you simply copy `lib/ ` into your src codebase and import from it instead of `nestjs-redis` app will work just fine.

That is why [this "weird" solution](https://github.com/skunight/nestjs-redis/issues/82#issuecomment-877677986
) works
And while this [PR](https://github.com/skunight/nestjs-redis/issues/82#issuecomment-886147579) is valid, it is not needed too.

If you are using yarn, you probably can just install the package from github and import from `lib/`
npm will try to run [prepublish](https://github.com/skunight/nestjs-redis/blob/master/package.json#L14) and fail on non-existing yarn.
You can fiddle with postinstall command of your project to pull the dependency from gitlab.

I personally will just copy the `lib/` into my codebase and hope the package will eventually get the update.

**Closed** 2021-10-11 01:39 UTC

**Comment by zackarychapple** [comment] 2021-11-04 13:12
> git+https://github.com/skunight/nestjs-redis.git

Confirmed that this worked for me as well.  Hope to see this updated as using git+https is not as reliable for protecting against breaking changes.

**Comment by volodyad** [comment] 2021-12-23 12:13
> > git+https://github.com/skunight/nestjs-redis.git
> 
> Confirmed that this worked for me as well. Hope to see this updated as using git+https is not as reliable for protecting against breaking changes.

You could connect to git commit   "nestjs-redis": "git+https://github.com/skunight/nestjs-redis.git#939f33a7f9b252e872c6edb76a3a860ed053bacf", it will be safer at least

**Comment by pietrovismara** [comment] 2022-01-24 13:25
@skunight any change of getting this fix in the latest on npm?

**Comment by Distortedlogic** [comment] 2022-01-24 20:12
bump

**Comment by robertsLando** [comment] 2022-01-25 16:49
Solution: `npm install @liaoliaots/nestjs-redis`

**Comment by Distortedlogic** [comment] 2022-01-26 12:41
@robertsLando `src/index.ts(8,30): error TS2307: Cannot find module 'nestjs-redis' or its corresponding type declarations.` uors did not work for me :/

**Comment by robertsLando** [comment] 2022-01-26 14:40
@Distortedlogic you have to import `@liaoliaots/nestjs-redis` not `nestjs-redis`

**Comment by stefan030** [comment] 2022-01-31 09:00
> @Distortedlogic you have to import `@liaoliaots/nestjs-redis` not `nestjs-redis`

Still getting similar error after trying out liaoliaots' package. 

Nest can't resolve dependencies of the Symbol(create-nestjs-middleware-module:options) (?, ConfigService). Please make sure that the argument RedisService at index [0] is available in the CoreModule context.

My nestjs version is 8.2.6

**Comment by stefan030** [comment] 2022-01-31 09:03
As well as: 
The redis client-provider 'Symbol(default)' was not found in the application context.

**Comment by Distortedlogic** [comment] 2022-01-31 11:25
@stefan030 read the docs... this redis module cannot just be dropped inplace of the other. The config options have a different structure.. also, the module is global only! so u cannot import RedisModule into other modules, instead since its global just inject the service.

**Comment by robertsLando** [comment] 2022-01-31 13:05
TLDR;:

```
import { RedisModule } from '@liaoliaots/nestjs-redis';

/* ....  /* 
 RedisModule.forRoot({
      closeClient: true,
      config: {
        host: 'localhost',
        port: 6380,
      },
    }),

```

**Comment by JustDoItSascha** [comment] 2022-02-16 14:40
No release yet?

**Comment by Halinen** [comment] 2022-02-18 04:20
尝试用yarn更新了半天，最后直接把fix的版本clone了下来解决了- -

**Comment by JuKu** [comment] 2022-02-18 22:20
@robertsLando Thank you very much! :)

**Comment by ymc9** [comment] 2022-07-26 01:09
It turns out that for liaoliaots package RedisModule is by default global, you'll run into error if you import it into another module...  Remove the import and the error is gone.

**Comment by Celleb** [comment] 2022-08-18 08:53
> @rares-lupascu Nice workaround for local 😎 !!
> 
> But for production, when can we expect a fix on this?

You can use  https://www.npmjs.com/package/patch-package

```shell
npx patch-package nestj-redis
```

This will apply your changes every time you install or reinstall the package

**Comment by phillippelevidad** [comment] 2024-04-02 20:31
> This issue is still exist while installing with npm. Looks like you need to republish your npm package. Currently, I'm overcome this issue by changing the package.json
> 
> ```
> "nestjs-redis": "git+https://github.com/skunight/nestjs-redis.git",
> ```
> 
> ![image](https://user-images.githubusercontent.com/20408623/137195021-a66b30d8-483b-40e9-ad1d-269c95bbfe26.png)

This still seems to be the best solution in 2024!
